version: 2

models:
  - name: customer_analytics
    description: "Customer analytics with aggregated metrics"
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
      - name: total_orders
      - name: total_spent
      - name: avg_order_value
        
  - name: business_kpis
    description: "Business KPIs and metrics"
