version: 2

models:
  - name: dim_customers
    description: "Cleaned customer dimension table"
    columns:
      - name: customer_key
        description: "Surrogate key for customer"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Natural key for customer"
        tests:
          - not_null
      - name: first_name
      - name: last_name
      - name: email
        tests:
          - not_null
          
  - name: fct_orders
    description: "Cleaned fact table for orders"
    columns:
      - name: order_key
        tests:
          - not_null
          - unique
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
