
models:
  - name: raw_customers_json
    description: "Raw customer data from JSON files"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: customer_data
        description: "Raw JSON customer data"
        
  - name: raw_orders_csv
    description: "Raw orders data from CSV files"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
